spring.application.name=kafka-quick-start

spring.kafka.bootstrap-servers=localhost:9092

# If each microservice needs to process all messages from a topic independently, they should have different
# group.id values. This ensures that each microservice receives all messages.
# If multiple instances of a microservice should share the workload, they should have the same group.id value.
spring.kafka.group-id=foo

spring.kafka.topic.name=quickstart-events
